include:
  - local: .gitlab/ci/workflows/matrix_build_npm.yml

# NPM Publish ==========================================================================================================
npm:
  extends:
    - .matrix_build_npm
  stage: build
  trigger:
    include:
      - component: $CI_SERVER_FQDN/shortlink-org/gitlab-templates/npm_publish@main
    strategy: depend
#  rules:
#    - if: $CI_COMMIT_TAG
#      when: on_success
